name: Image
on: push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --file Dockerfile.dummy --build-arg NF_IMAGE_VERSION=$GITHUB_SHA -t netlify/build:$GITHUB_SHA
      - name: Pull Xenial
        run: docker pull netlify/build:xenial
      - uses: vbrown608/whalescale@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          currentTag: netlify/build:${{ github.sha }}
          defaultTag: netlify/build:xenial
