name: Check-Size

on: push

jobs:
  check-size:
    name: Check image size
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build . --file Dockerfile.dummy --build-arg NF_IMAGE_VERSION=$GITHUB_SHA -t netlify/build:$GITHUB_SHA
      - name: Check image size
        run: |
          SIZE=$(docker image inspect netlify/build:$GITHUB_SHA --format='{{.Size}}')
          curl -d '{"name":"Image size", "head_sha":"${{ github.sha }}", "conclusion":"neutral", "output":{"title":"$SIZE", "summary":"foo"}}' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
            -X POST https://api.github.com/repos/${{ github.repository }}/check-runs
      # - uses: LouisBrunner/checks-action@v1.1.1
      #   if: always()
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     name: Test XYZ
      #     conclusion: neutral
      #     output: |
      #       {"title":"Size is ${{ steps.size.outputs.size }}", "summary": "ok"}
